label define lbl_yn 0 "No" 1 "N/A"
label define lbl_pvisits 0 "CSO has never visited" 1 "1 prior visits" 2 "2 prior visits" 3 "3 prior visits" 4 "4 prior visits" 55 ">4 prior visits" .b "Missing: answer left blank" .u "Missing: unknown"


if instrument == 1 {
    label var county "County"
    label var zone "Zone/Cluster"
    local ynvals "vis_before vis_act_kids vis_act_ht vis_act_fdbk vis_act_gen vis_act_other vis_act_na cso_usetab_yn cso_usepcl_yn cso_usetab_pup_yn cso_gave_fdbk_yn cso_usetab_fdbk_yn cso_fdbk_remember cso_fdbk_showtab_yn cso_shw_tips cso_shw_fluency cso_shw_video cso_shw_lsnd cso_shw_other cso_shw_na cso_ref_prev_fdbk_yn cso_fdbk_better_tus cso_fdbk_better_nont cso_fdbk_discfluency cso_fdbk_flu_useful cso_tab_distract_yn cso_tab_fdbk_distrac cso_pres_ass_tab cso_pup_distract_ass tchr_ass_pup_flu_yn tch_mob_phone tch_has_android tch_wants_assess"
    foreach item of local ynvals {
        replace `item' = "0" if `item' == "No"
        replace `item' = "1" if `item' == "Yes"
        destring `item', replace
        label val `item' lbl_yn
    }
    replace vis_before_freq = "1" if vis_before_freq == "1x"
    replace vis_before_freq = "2" if vis_before_freq == "2x"
    replace vis_before_freq = "3" if vis_before_freq == "3x"
    replace vis_before_freq = "4" if vis_before_freq == "4x"
    replace vis_before_freq = "55" if vis_before_freq == "More than 4x"
    replace vis_before_freq = ".b" if vis_before_freq == ""
    replace vis_before_freq = "0" if vis_before_freq == "N/A; CSO has never visited"
    replace vis_before_freq = ".u" if vis_before_freq == "Don't Know"
    destring vis_before_freq, replace
    label val vis_before_freq lbl_pvisits
}
/*
if instrument == 2 {
    label var county "County"
    label var zone "Zone"
    label var designation "Designation"
    label var tablet_yn "Tusome has issued tablet"
    label var recd_tab_yr "Year tablet received"
    label var recd_tab_month "Month tablet received"
    label var freqapps_unprompt "Unprompted list of apps used to support Tchrs"
    label var freqapps_tt_promp "Apps frequently used to support Tchrs: Tutor"
    label var freqapps_papaya_promp "Apps frequently used to support Tchrs: Papaya"
    label var freqapps_bks_promp "Apps frequently used to support Tchrs: Digital books"
    label var freqapps_vids_promp "Apps frequently used to support Tchrs: Videos"
    label var app_freq1 "Most-frequently used app: #1"
    label var app_freq2 "Most-frequently used app: #2"
    label var app_freq3 "Most-frequently used app: #3"
    label var app_freq4 "Most-frequently used app: #4"
    label var changes_prev_lesson "Changes to Tangerine app noticed: prev lesson record"
    label var changes_schvis_rep "Changes to Tangerine app noticed: school visit report"
    label var changes_other "Changes to Tangerine app noticed: other"
    label var changes_other_det "Changes to Tangerine app noticed: details of other"
    label var useful_tang_open "Things CSO finds useful about Tangerine app for observations"
    label var ref_tang_fdbk "CSO refers to Tangerine during feedback"
    label var ref_tang_fdbk_det "Details of what CSO refers to from Tangerine during feedback"
    label var ref_tang_fdbk_maxuse "What CSO finds most useful from Tangerine during feedback"
    label var tang_fdbk_notuseful "Any items of feedback report not useful?"
    label var tang_fdbk_notuse_det "Details of not useful elements in feedback report"
    label var refer_tang_nonobs "CSO refers to Tangerine to help plan work"
    label var tang_nonobs_decision "Examples of how CSO uses Tangerine to help plan work"
    label var freq_refer_tang_plan "Frequency with which CSO refers to Tangerine for planning"
    label var tang_nonobs_nowhynot "Reason CSO doesn't refer to Tangerine for planning"
    label var db_chk_prevterm_freq "# of times CSO checked TangDB"
    label var cdir_comm_reres "County Dir communicates about TangDB results"
    label var cdir_comms_topic "Topic of County Dir communication re TangDB results"
    label var cdir_comms_inf_ex "Comms from County Dir influences work"
    label var relx_better_tchr "Relationship has changed for the better: Tchr"
    label var relx_worse_tchr "Relationship has changed for the worse: Tchr"
    label var relx_nochg_tchr "Relationship is unchanged: Tchr"
    label var relx_better_ht "Relationship has changed for the better: HT"
    label var relx_worse_ht "Relationship has changed for the worse: HT"
    label var relx_nochg_ht "Relationship is unchanged: HT"
    label var relx_better_tscscd "Relationship has changed for the better: TSC-Subcounty Dir"
    label var relx_worse_tscscd "Relationship has changed for the worse: TSC-Subcounty Dir"
    label var relx_nochg_tscscd "Relationship is unchanged: TSC-Subcounty Dir"
    label var relx_better_tsccd "Relationship has changed for the better: TSC-County Dir"
    label var relx_worse_tsccd "Relationship has changed for the worse: TSC-County Dir"
    label var relx_nochg_tsccd "Relationship is unchanged: TSC-County Dir"
    label var relx_better_moescd "Relationship has changed for the better:MOE-Subcounty Dir"
    label var relx_worse_moescd "Relationship has changed for the worse:MOE-Subcounty Dir"
    label var relx_nochg_moescd "Relationship is unchanged: MOE-Subcounty Dir"
    label var relx_better_moecd "Relationship has changed for the better: MOE-County Dir"
    label var relx_worse_moecd "Relationship has changed for the worse: MOE-County Dir"
    label var relx_nochg_moecd "Relationship is unchanged: MOE-County Dir"
    label var prof_relx_chg_det "Details of how professional relationships have changed"
    label var db_part_inf_dec "TangDB element that influences decision-making"
    label var tang_new_tab "New function/report/data desired for Tang on tablet"
    label var tang_new_db "New function/report/data desired for TangDB"
    label var cdir_conseq_yn "County Dir has announced consequences b/c of TangDB"
    label var cdir_conseq_det "Details of consequence"
    label var filename "Source file"
    }

if instrument == 3 {
    label var county "County"
    label var zone "Zone"
    label var designation "Interviewee role"
    label var desig_other_det "Role other than listed"
    label var intro_db_yr "Year introduced to Dashboard"
    label var intro_db_month "Month introduced to Dashboard"
    label var src_pre_db_decaid "Pre-TangDB info source for mgmt decisions"
    label var get_link_yn "Receives link"
    label var get_link_freq "Frequency with which link received"
    label var get_link_modality "Mechanism by which link is received"
    label var db_lnk_chk_sday "Checks link the same day it's received"
    label var db_lnk_chk_sweek "Checks link the same week it's received"
    label var db_lnk_chk_smonth "Checks link the same month it's received"
    label var db_lnk_chk_dont "Doesn't check link once received"
    label var db_lnk_chk_dont_why "Reason doesn't check the link"
    label var db_lnk_chk_na "N/A: doesn't receive link"
    label var db_unp_devices "Unprompted listing of devices used to receive link"
    label var db_prmp_dev_phone "Link received on phone"
    label var db_prmp_dev_tab "Link received on tablet"
    label var db_prmp_dev_laptop "Link received on laptop"
    label var db_prmp_dev_desktop "Link received on desktop"
    label var db_prmp_dev_colleague "Link received on colleague's computer"
    label var db_prmp_dev_other "Link received on other device"
    label var db_prmp_dev_other_det "Link received on other device (details)"
    label var db_dev_access_na "N/A: doesn't access DB"
    label var db_lnk_frm_other_yn "Receives link from non-RTI employee"
    label var db_lnk_frm_other_det "Non-RTI link source"
    label var no_lnk_wnt_yn "If doesn't receive link, would like to get one?"
    label var no_lnk_wnt_freq "Frequency with which would like to receive link"
    label var del_mech_unprompted "Unprompted preferred mechanism to receive link"
    label var del_mech_prp_sms "Preferred mechanism to receive DB access: SMS"
    label var del_mech_prp_wa "Preferred mechanism to receive DB access: WhatsApp"
    label var del_mech_prp_email "Preferred mechanism to receive DB access: Email"
    label var del_mech_prp_app "Preferred mechanism to receive DB access: Dedicated App"
    label var del_mech_prp_other "Preferred mechanism to receive DB access: Other"
    label var del_mech_prp_det "Preferred mechanism to receive DB access: Specifics of Other"
    label var db_sect_consulted "Sections of TangDB consulted most often"
    label var db_chk_freq "Frequency checks TangDB"
    label var mgmt_dec_from_db "Mgmt decisions based on TangDB"
    label var db_info_wnt_yn "Is there data desired but not on TangDB?"
    label var db_info_wnt_det "Details of desired-but-not-available data"
    label var diff_mgmt_nodata_yn "Are there daily mgmt decisions difficult b/c lack of data?"
    label var diff_mgmt_nodata_det "Details of difficult daily mgmt decisions"
    label var db_rev_feat_det "Desired TangDB revisions"
    label var filename "Source file"
}
*/